### ISSUE TITLE
About the sigma parameter in your code implementation

### ISSUE THREAD

**Issue by zhao-yiqun** [1zb/3DILG#14]
Hi Biao,

I found that in your code there is a sigma parameter [sigma](https://github.com/1zb/3DILG/blob/master/modeling_vqvae.py#L460). I saw that in the loss function, you decay it to zeros,  I don't know what is the purpose of setting this. Could you please give me some feedbacks?

Thanks in advance.

**Comment by 1zb** [comment]
Hi Yiqun,

The sigma here is the "inverse sigma" in Gaussian kernel (sorry for the wrong symbol)
https://en.wikipedia.org/wiki/Radial_basis_function_kernel

The sigma controls the smoothness of interpolated features (the smaller, the smoother).

**Comment by zhao-yiqun** [comment]
Thanks !
