### ISSUE TITLE
quick question on dataset 

### ISSUE THREAD

**Issue by xwhan** [1zb/3DILG#4]
Hi @1zb,

Thank you for sharing your work! Since you haven't released the processed data, can you explain what does "vol_points" and "near_points" mean in your code? Are those the outputs of the mesh-fusion pipeline as well?

https://github.com/1zb/3DILG/blob/4359ceee418de68c4dd2600a7ef5b36263fb9e01/shapenet.py#L125

**Comment by 1zb** [comment]
`vol_points` means points uniformly sampled in the bounding volume ( [-1, 1] x [-1, 1] x [-1, 1]).
`near_points` means points sampled near the surface (it is helpful to reconstruct high-quality shapes).
You can use any SDF softwares/packages to generate your own data.

**Comment by xwhan** [comment]
Thank you! I found a similar pipeline in occupancy_networks's repo.
