### ISSUE TITLE
normalization? 

### ISSUE THREAD

**Issue by xwhan** [1zb/3DILG#5]
Hi @1zb,

I have another question regarding to data processing? Does the model expect normalized point cloud, SDF coordinates (e.g., transform all points to be within [-0.5, 0.5] ^ 3)? It seems that you scaled the points cloud but not the SDF points?
https://github.com/1zb/3DILG/blob/master/shapenet.py#L134

I'm also curious why the "Axis transform" is only applied on training data. Is this a common practice? -- sorry that I'm new to this line of work :)
https://github.com/1zb/3DILG/blob/master/datasets.py#L33

Thanks in advance!

**Comment by 1zb** [comment]
> Does the model expect normalized point cloud, SDF coordinates (e.g., transform all points to be within [-0.5, 0.5] ^ 3)?
You are correct about this. Points are scaled to [-1, 1] in our experiments. However, other scales should work too, e.g., [-0.5, 0.5].

> It seems that you scaled the points cloud but not the SDF points?
We generate SDF by ourselves. They are already scaled.

> I'm also curious why the "Axis transform" is only applied on training data. Is this a common practice? -- sorry that I'm new to this line of work :)
Axis transform is a data augmentation technique. We do not need it when testing.

Best,
Biao

**Comment by supersyz** [comment]
Hi, Congratulations on your great work! 
Would you mind tell me how you calculate the scale values from xxx.npy,which is applied to the point clouds?
https://github.com/1zb/3DILG/blob/master/shapenet.py#L134
